name: Spigot gradle build

on:
  push:
    branches:
      - '*'
    paths:
      - monitor-spigot/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
    - name: Restore gradle.properties
      env:
        GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      shell: bash
      run: |
        cd monitor-main
        echo "${GRADLE_PROPERTIES}" > gradle.properties
    - name: Build with gradle
      run: |-
        cd monitor-spigot
        ./gradlew build
    - name: Publish with gradle
      run: |-
        cd monitor-main
        ./gradlew publish